# Generated by Django 5.0.5 on 2024-05-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=255)),
                ('pro_price', models.CharField(max_length=255)),
                ('pro_image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
