# Generated by Django 5.0.5 on 2024-05-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_image',
            field=models.FileField(null=True, upload_to='products'),
        ),
    ]
