# Generated by Django 5.0.6 on 2024-05-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_cat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
