# Generated by Django 5.0.6 on 2024-05-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_products_pro_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pro_cat',
            new_name='pro_catid',
        ),
    ]
