# Generated by Django 5.0.6 on 2024-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reg_image',
            field=models.FileField(null=True, upload_to='profile'),
        ),
    ]
