# Generated by Django 5.0.6 on 2024-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_registration_reg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_user', models.CharField(default=None, max_length=250)),
                ('wish_proid', models.IntegerField(null=True)),
                ('wish_name', models.CharField(max_length=250)),
                ('wish_price', models.FloatField(max_length=250)),
                ('wish_image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='reg_image',
        ),
    ]
