# Generated by Django 5.0.6 on 2024-06-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_wishlist_remove_registration_reg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_message', models.TextField()),
                ('noti_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
