# Generated by Django 5.0.6 on 2024-06-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
