# Generated by Django 5.0.6 on 2024-06-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_notification_noti_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reg_image',
            field=models.FileField(null=True, upload_to='profile'),
        ),
    ]
