# Generated by Django 5.0.6 on 2024-08-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_registration_reg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='noti_date',
            field=models.DateTimeField(null=True),
        ),
    ]
